name: single_storage_base
description: A platform agnostic key-value storage interface for Dart & Flutter.
version: 1.0.0
homepage: https://www.github.com/modulovalue/single_storage_base
issue_tracker: https://github.com/modulovalue/single_storage_base/issues
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>=2.4.4 <3.0.0'

dev_dependencies:
  extra_pedantic: ^1.1.1
  test: ^1.5.0
  mockito: ^4.1.1
  test_coverage: ^0.2.0