name: single_storage_base.dart
description: A platform agnostic key value storage interface
version: 0.1.0
homepage: https://www.github.com/modulovalue/single_storage_base.dart
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>

environment:
  sdk: '>=2.4.4 <3.0.0'

dev_dependencies:
  extra_pedantic: ^1.1.1
  test: ^1.5.0
  mockito: ^4.0.0